/**
 * Hand-emitted PASSAGE (ADR-0008 lane 1): produce the exact artifacts the
 * vendor CLI would hand us — a pixi-format bundle manifest plus the HH law
 * wrapper — without needing @assetpack/core's native toolchain. The consumer
 * path (parse → sampler law → TextureStyle.defaultOptions → app.init) is
 * identical for hand-emitted and vendor-built manifests; only `emitter`
 * differs, and both ride the same schema.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { FIVE_ASSET_SLOTS, loadKitJson, type HhSkinKit } from "./kit.ts";
import {
  HH_MANIFEST_SCHEMA_ID,
  parseHhAssetManifest,
  serializeHhAssetManifest,
  type HhAssetManifest,
} from "./manifest.ts";
import { defaultSamplerLaw } from "./sampler.ts";
import type { KitBuildSpec } from "./kits.ts";

/** Textures ordered meter-first: the §8.10 authoring law made visible in data. */
export function buildHhManifest(spec: KitBuildSpec, kit: HhSkinKit): HhAssetManifest {
  const doc: unknown = {
    schema: HH_MANIFEST_SCHEMA_ID,
    kit: kit.name,
    emitter: "hand-emitted",
    defaults: { ...defaultSamplerLaw() },
    textures: FIVE_ASSET_SLOTS.map((slot) => ({
      alias: spec.aliasFor(slot),
      src: kit.assets[slot].file,
      sampler: {},
    })),
    // pixi-format layer: AssetPack puts tags inside `data` (verified against
    // core 1.7.0 typings), so the hand-emitted bundle mirrors that exactly.
    pixiManifest: {
      bundles: [
        {
          name: kit.lineage,
          assets: FIVE_ASSET_SLOTS.map((slot) => ({
            alias: spec.aliasFor(slot),
            src: kit.assets[slot].file,
            data: { tags: [...spec.assetTags] },
          })),
        },
      ],
    },
  };
  // Parse through the SAME boundary the runtime consumer uses — the emitter
  // can only ever ship what the parser would accept.
  return parseHhAssetManifest(doc);
}

export function writeHhManifest(repoRootDir: string, spec: KitBuildSpec): string {
  const kit = loadKitJson(join(repoRootDir, spec.kitDir));
  const manifest = buildHhManifest(spec, kit);
  const target = join(repoRootDir, spec.manifestPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, serializeHhAssetManifest(manifest));
  return target;
}

/** Generate the vendor-CLI config (`.assetpack.mjs`) from the same spec data,
 *  so running the real CLI later cannot silently disagree with the skeleton. */
export function renderVendorConfig(spec: KitBuildSpec): string {
  return `// GENERATED by @hh/assetpack (src/kits.ts → emit-config) — do not hand-edit.
// Vendor-CLI entry (ADR-0008 lane 1), from tools/assetpack with @assetpack/core installed:
//   node_modules/.bin/assetpack -c configs/${spec.kit}.assetpack.mjs
// (core 1.7.0 ships the CLI itself; its --version banner lies about 0.2.0 — ignore it.)
// Paths resolve relative to THIS FILE, so the CLI works from any cwd.
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { pixiPipes } from "@assetpack/core/pixi";

const here = dirname(fileURLToPath(import.meta.url));

export default {
  entry: resolve(here, "../../../${spec.kitDir}"),
  output: resolve(here, "../../../${spec.outputDir}"),
  strict: true,
  ignore: ["kit.json", "manifest/**"],
  pipes: [
    pixiPipes({
      cacheBust: false,
      resolutions: { default: 1 },
      compression: false, // GPU-texture/binary compression OFF until real art lands (also dodges gpu-tex-enc)
      texturePacker: {
        allowRotation: ${spec.texturePacker.allowRotation},
        shapePadding: ${spec.texturePacker.shapePadding},
        forceSquared: ${spec.texturePacker.forceSquared},
      },
      manifest: { output: "hh-pixi-manifest.json", includeMetaData: true },
    }),
  ],
  assetSettings: [{ files: ["**/*.png"], metaData: { ${spec.assetTags.map((tag) => `${tag}: true`).join(", ")} } }],
};
`;
}

export function writeVendorConfig(configsDir: string, spec: KitBuildSpec): string {
  mkdirSync(configsDir, { recursive: true });
  const target = join(configsDir, `${spec.kit}.assetpack.mjs`);
  writeFileSync(target, renderVendorConfig(spec));
  return target;
}
